### ISSUE TITLE
Jingle session terminated immediately

### ISSUE THREAD

**Issue by Natureshadow** [jappix/jappix#369]
When trying to start an audio call, it is signalled to the remote without probllems, but when the cal is accepted then the Jingle session is terminated (with success) immediately.

Console logs suggest that the negotiation is completed, including ICE and all that, and then a clean termination is signalled.

**Comment by emamirazavi** [comment]
I have the same problem!!! Valerian please note, i have log files about caller and callee. See them, Can you help to solve the problem.
Caller log file: http://pastebin.com/nkYiTPkh
Callee log file: http://pastebin.com/qt552Hpd
