### ISSUE TITLE
"rid too large" error

### ISSUE THREAD

**Issue by tsumi** [jappix/jappix#398]
Hi,
with Jappix >= 0.9.4, using BOSH proxy, when i connect with my jabber account contact list/avatar aren't loaded and jabber server (prosody 0.8.2) return on logs:

```
rid too large (means a request was lost). Last rid: 635112 New rid: 635114
```

This problem doesn't happen with Jappix 0.9.3.

If you need more logs/checks/test just ask.

Thanks :)

**Comment by postblue** [comment]
Sorry for necro-posting. I have the error too with prosody trunk nightly build 568 (2015-07-08, d01c29b62b16), Debian Jessie.
