### ISSUE TITLE
Connection to BOSH server times out at certain command

### ISSUE THREAD

**Issue by steffen-mueller** [jappix/jappix#429]
I have installed jappix on a server and created a local proxy forwarding for the ejabberd HTTP Bind URL like described in the documentation. The URL is reachable and can be used by Jabbix to log in. But after logging in, the HTTP Request times out - there is no message in the ejabberd logs about the request or a missing response.

The Request XML is (XXX by me):

```
<body xml:lang='de' rid='189499' sid='XXX' xmlns='http://jabber.org/protocol/httpbind' key='XXX' >
  <iq xmlns="jabber:client" to="im.XXX.de" type="get" id="1" xml:lang="de">
    <query xmlns="http://jabber.org/protocol/disco#info"/>
  </iq>
  <iq xmlns="jabber:client" type="get" id="2" xml:lang="de">
    <query xmlns="jabber:iq:roster"/>
  </iq>
  <iq xmlns="jabber:client" type="get" id="3" xml:lang="de">
    <query xmlns="jabber:iq:privacy"/>
  </iq>
  <iq xmlns="jabber:client" type="get" id="4" xml:lang="de">
    <query xmlns="jabber:iq:private">
      <storage xmlns="storage:rosternotes"/>
    </query>
  </iq>
  <iq xmlns="jabber:client" to="im.XXX.de" type="get" id="5" xml:lang="de">
    <services xmlns="urn:xmpp:extdisco:1"/>
  </iq>
</body>
```

I know that maybe you are the wrong ones to talk to as the ejabberd response does not seem to arrive - but as the other responses work, the proxy is set up correctly and the BOSH HTTP Bind is reachable, I'm a little clueless.

The proxy config in case you wondered:

```
<VirtualHost 10.8.0.1:80>
        ServerAdmin server@XXX.de
        ServerName  chat.XXX

        ProxyRequests Off

        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>

        ProxyPass /http-bind  http://XXX:5280/http-bind
        ProxyPassReverse /http-bind   http://XXX:5280/http-bind
        Header set Access-Control-Allow-Origin "*"

        ProxyPass / http://127.0.0.1:1083/
        ProxyPreserveHost On
</VirtualHost>
```

This is the virtualhost delivering jappix itself (running in a VM that is proxied on 1083).

**Comment by valeriansaliou** [comment]
We fixed this in v1.1.2.
Sorry for being late, hope it fixes your issue. If not, please notify me and I'll re-open.
