### ISSUE TITLE
Having problem enabling registration

### ISSUE THREAD

**Issue by silveryseven** [jappix/jappix#504]
the responses are these:

    <body xmlns:stream='http://etherx.jabber.org/streams' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh' ver='1.6' inactivity='30' wait='120' polling='5' secure='true' hold='1' from='ausazko.com' authid='fc91ba49-97c6-49b8-9889-a15208237e18' requests='2' sid='fc91ba49-97c6-49b8-9889-a15208237e18' xmlns='http://jabber.org/protocol/httpbind'><stream:features><register xmlns='http://jabber.org/features/iq-register'/><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>EXTERNAL</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms></stream:features></body>

    <body sid='fc91ba49-97c6-49b8-9889-a15208237e18' xmlns:stream='http://etherx.jabber.org/streams' xmlns='http://jabber.org/protocol/httpbind'><iq id='reg1' type='error' xmlns='jabber:client'><error type='cancel'><not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq></body>```

    <body type='terminate' xmlns:stream='http://etherx.jabber.org/streams' xmlns='http://jabber.org/protocol/httpbind'/>```

Jappix says "Jappix has been interrupted by a network issue, a bug or bad login (check that you entered the right credentials), sorry for the inconvenience."

I tried doing the the fixes on other issues related with this kind of issue but nothing works hope you can help me fix this on mine

**Comment by valeriansaliou** [comment]
Closed as too old.
