### ISSUE TITLE
avatar in rooms

### ISSUE THREAD

**Issue by cartman10mpi** [jappix/jappix#521]
Hello
Avatars uploaded for users are not shown in rooms and room chats ! just the default avatar is shown 
in microblogging and contact list and private chats between two contacts avatars are fine . just in public rooms 

using openfire + jappix primo
Thanks

**Comment by valeriansaliou** [comment]
Cannot reproduce.
However, some MUC servers block vCard IQ requests. Depending on the MUC server you're using, this might be normal.
