### ISSUE TITLE
IE11 - can't connect due to broken xml lang (NS1)

### ISSUE THREAD

**Issue by youleaf** [jappix/jappix#522]
As for issue #200, but this time on IE11.
Tried to find the relevant code of commit 2f410c7 in master to make a pull request, but no luck, so I monkeypatched my mini.js as following (I'll paste the whole setXMLLang function for clarity):

    JSJaCPacket.prototype.setXMLLang = function(xmllang) {
      // Fix IE bug with xml:lang attribute
    
      // Also due to issues with both BD and jQuery being used, employ a simple regexp since the detection
      // here is very limited.
      // "Trident" matches IE10 and IE11 (and hopefully future versions)
      if ((navigator.appVersion.match(/^.*MSIE (\d)/)) || (navigator.appVersion.match(/Trident/)))
        return this;
      if (!xmllang || xmllang == '')
        this.getNode().removeAttribute('xml:lang');
      else
        this.getNode().setAttribute('xml:lang',xmllang);
      return this;
    };

It works with IE11 in my deployment (ejabberd / bosh). You can test this live on www.impresa8108.it - let me know if you find any issue.

**Comment by valeriansaliou** [comment]
Thanks, fixed using your patch.
