### ISSUE TITLE
Command /whois <jid> not working

### ISSUE THREAD

**Issue by guarak** [jappix/jappix#531]
When a user A want infos about a person B who are connected in the same chatroom, if the user A sends the command /whois <jid>, it answers that user B is not connected in this chatroom....

**Comment by valeriansaliou** [comment]
Cannot replicate.

Can you suggest me the conditions of the bug? (room name, room configuration, are user's JID publicly discoverable?)

**Comment by guarak** [comment]
OK, my mistake !
Indeed, it's working, beut in my project we had a issue with rthe nicknames and the JID..
Now i've edited the profiles and it works...

Thankx for your return, the issue can be closed.
