### ISSUE TITLE
XSS in user directory

### ISSUE THREAD

**Issue by V1RTUOZ** [jappix/jappix#533]
Found XSS in user directory (latest git version).
Filter user input, please.
![jappix-xss.png](http://habrastorage.org/files/8cc/cca/4e3/8cccca4e36884c3fb566f8e80af91b62.png)

Possible, i can fix it and submit a pull-request.

**Comment by valeriansaliou** [comment]
Yes sure, please submit a PR.
Thanks for the findings!
