### ISSUE TITLE
Cross-Site Scripting vulnerability in Jappix

### ISSUE THREAD

**Issue by luisgf** [jappix/jappix#568]
An XSS has been detected in Jappix. Passing a special crafted parameter string via GET, the following JavaScript code is executed:

https://www.your.domain/jappix/?02d31"><script>alert(1)</script>f90ef=1

The fix is really easy. Adding a htmlentities at line 104 in server/desktop.php fix the vuln.

**Comment by valeriansaliou** [comment]
Thanks for the report, the issue is now fixed. Let me know if things look good for you now.
